# Docker image
image: continuumio/miniconda3:latest

before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda install -y numpy pandas scipy pytest h5py bcolz 
  - conda install -c bioconda bedtools htslib pyvcf
  # dl toolkit
  - pip install tensorflow
  - pip install keras
  # cython in case we need it
  - pip install cython
  # - conda install -y pytorch torchvision -c soumith


tests:
  stage: test
  tags:
    - docker
  script:
    - python --version
    - conda --version
    - pip install .
    - py.test
