# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox
  - pip install -r requirements_dev.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - tox -e ${TOXENV}
  - ls
  - pyensembl install --reference-name hg38_test --annotation-name hg38_chr22_test --gtf "./tests/data/gencode.v24.annotation_chr22.gtf" --transcript-fasta "./tests/data/hg38_chr22.fa"
  - pyensembl install --reference-name hg38_test_FivePrimeUTRSeq_minus --annotation-name hg38_chr22_test_FivePrimeUTRSeq_minus --gtf "./tests/data/gencode.v24.annotation_chr22_FivePrimeUTRSeq_testing_minus-strand.gtf" --transcript-fasta "./tests/data/hg38_chr22.fa"
