import pytest
from gfeat.upstreamATG import UpstreamATG


@pytest.fixture()
def seq_list():
    list = ["ATCCCCTGATGGACTGGAAGCCTACCCCCCACCCCAAGCCCTGGCTGCGACAGCTCTGGAACCCTGACTGCCTGGGTG"
            "CCCCTCAGCTCTGGAACCCTGACTGCCTGGATGCTCCTCAGCTCTGGAACCCTGACTGCTTGGATACCCCCTCAGCTC"
            "TGGAACCCTGACTGCCTGGAACCGTGATCCGGAACCCAAGATCCTTTCAAGGCCTCAGGGGTATTGCTGCTGCCCTCC"
            "TCCTTCTCAATTTAACCCCGCGTCCAGCCGTCGCCACCAGGGGCGTCAGAGCGCGCGCATGCTCCTAGCTCGGAGCCG"
            "CGCCGATCTCGCGCCGGCACCTGGCAGCCAATCGCAGGTCTCCACTGGACGCGCGCGTGTGGAGGCGTGCGCGTCGGC"
            "GGCGCCGGGGGCCTGAGGAGGCGTAGTCGCCGCCGGCTGTGCCCCGGGAGCGCCTCCGGGGCTGGTGCGTGGCCGGCA"
            "GCTCGCGAACAGCAGCTGATCCGGACTG",
            "GATGTGACCTTCTGCCTGGAATAGCTCAAGTTCTTAAAAGTTGCGTTGTAATAAACCTGAG",
            "GCTGGGAAGTTCAAGATCAAGATGCTGGACGATTTGGTTCCTTAGTGAAGGCTCTCTTCCTGGCTGGTGGATGACAGC"
            "CTTCTTGCTGTGTTCTCACATGACAGAAAGAGGAAGCAAG",
            "GTGGCAGTTTATATAAAGGAAGCATTGGGACTTGTGGCCCCACCATTCAGGAATAAAAAAATTAGAAA"]
    return list
