"""
Test CDS
"""

from tests.transcript.config import transcript2


def test_CDS(transcript2):
    res = transcript2.CDS()
    assert res == "ATGGTGGCTGAGGCTGGTTCAATGCCGGCTGCCTCCTCTGTGAAGAAGCCATTTGGTCTCAGAAGCAAGATGGGCAAGTGGTG" \
                  "CCGCCACTGCTTCGCCTGGTGCAGGGGGAGCGGCAAGAGCAACGTGGGCACTTCTGGAGACCACGACGATTCTGCTATGAAGA" \
                  "CACTCAGGAGCAAGATGGGCAAGTGGTGCTGCCACTGCTTCCCCTGGTGCAGGGGGAGCGGCAAGAGCAACGTGGGCACTTCT" \
                  "GGAGACCACGACGATTCTGCTATGAAGACACTCAGGAGCAAGATGGGCAAGTGGTGCTGCCACTGCTTCCCCTGCTGCAGGGG" \
                  "GAGCGGCAAGAGCAACGTGGGCACTTCTGGAGACCACGACGACTCTGCTATGAAGACACTCAGGAGCAAGATGGGCAAGTGGT" \
                  "GCTGCCACTGCTTCCCCTGCTGCAGGGGGAGCGGCAAGAACAAAGTGGGCCCTTGGGGAGACTACGACGACAGCGCTTTCATG" \
                  "GAGCCGAGGTACCACGTCCGTCGAGAAGATCTGGACAAGCTCCACAGAGCTGCCTGGTGGGGTAAAGTCCCCAGAAAGGATCT" \
                  "CATCGTCATGCTCAAGGACACTGACATGAACAAGAAGGACAAGCAAAAGAGGTAACCAGGCCTGGGCTGGGAGGAGGTGGGAT" \
                  "GTGGGAGGATGATGGGGACATACCCTCCTGGCCGGGGAGGAGGGGAGCCTGGTTTTCTTGCCTCCACAGGCCTCACACCACCC" \
                  "TGGATGTGGAAACCTCAGAGAGTTCAGGGCACAGGCCCCTTTATGAGCAGCAACACAAAAACAAAACTTTAGCTGATTTCCAA" \
                  "TCAAATCATAATTTCCTTCCTAGAACACGAATAGACTGTTTTGAAGTGATTTAACTCGCAACGTTGTCGATGCAGCAGATTAT" \
                  "TTTTAATGTACAGATTTTAAAACAATGTTCTATACATTAAAAAAGTGTATATTGAGAACTAAGAATGAAGCCCCATAACACAT" \
                  "CAACTTCAGGGCTAAATATTCTTCAAATAAAATCCAGTATGGATTTTATATCAATGTACACTATGTAAATATGTTCTTTACTG" \
                  "AGTAATCTTAGAAGGAAACTGAAATGGGAAGATGGTTCTTGTGCTTGAATAGGAAGATTGAATTTTCTGAAGATGTGAGCTTT" \
                  "TTGGCTGGGCGTGGTGGCTCACACCTGTAATCCCAGCACTTTGGGAGGCTGAGGAGGGCAGATCATGGGGTCAGGAGATCGAG" \
                  "ACCATCCTTGCTAACACGGTGAAACCCCGTCTCTACTAAAAAATATAAAAAAAATTAGCTGGACGCGGTGGCAGGCACCTGTA" \
                  "GTCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATGGCGTGAACCTGGGAGGCGGAGCTTGCAGTGAGCCGAGATCACGCCACT" \
                  "GTAGTAGAGCCTGGGAGACAGAGCAAGACTCCGTCTCAAAAAAAAAAAAAAAAAAAAGTGAGCTTTTTCTATTTATCACTTTT" \
                  "ACTTAAGCCAAATAAAAATAGCAGTTTTAGAGTTTTTAAATTACACATGCTGTCTTTTATTATTGTGCTAAGTTAATTTTTTT" \
                  "GTAGCAGAATGGACAAAGGCTTGCTTTTCCAGATGTCAAAATGTGCATGTTATTTATTTCC"
