"""
Test FivePrimeUTRSeq.__init__()
"""

import pytest
from tests.UTR.config_UTR import FivePrimeUTRSeq_object


def test_constructor(FivePrimeUTRSeq_object):
    res = FivePrimeUTRSeq_object.five_prime_utrs
    assert res == ['AGTGCAAACGCAGCGCCAGACACGCCCCGCCCGCGCCTCCCCGCCCCCCCGCGCCCGCGGCCCCAAGCGGTTCCCGAGCCCAGGCCCGCGCCGAGCCCAGGTGAGCGCCCGCCCCGGGGACCCTGGTCCCCGGAACCCCGGTCCCCGCCCGCCGCCCCGCCTCTTCGCCCCGGCGCCGGGGGCCAGCGCTTGCGCTCCCAAGTCTCGGACCCCGGCCCGGCACGTTAGGGGCTGGGGGTT',
                   'CGCGGCCCCAAGCGGTTCCCGAGCCCAGGCCCGCGCCGAGCCCAGGTGAGCGCCCGCCCCGGGGACCCTGGTCCCCGGAACCCCGGTCCCCGCCCGCCGCCCCGCCTCTTCGCCCCGGCGCCGGGGGCCAGCGCTTGCGCTCCCAAGTCTCGGACCCCGGCCCGGCACGTTAGGGGCTGGGGGTT',
                   'GCCCCAAGCGGTTCCCGAGCCCAGGCCCGCGCCGAGCCCAGGTGAGCGCCCGCCCCGGGGACCCTGGTCCCCGGAACCCCGGTCCCCGCCCGCCGCCCCGCCTCTTCGCCCCGGCGCCGGGGGCCAGCGCTTGCGCTCCCAAGTCTCGGACCCCGGCCCGGCACGTTAGGGGCTGGGGGTT',
                   'AAGCGGTTCCCGAGCCCAGGCCCGCGCCGAGCCCAGGTGAGCGCCCGCCCCGGGGACCCTGGTCCCCGGAACCCCGGTCCCCGCCCGCCGCCCCGCCTCTTCGCCCCGGCGCCGGGGGCCAGCGCTTGCGCTCCCAAGTCTCGGACCCCGGCCCGGCACGTTAGGGGCTGGGGGTTGGCAAGCGGGGCCAGAGGCACTGGCCGGGGTCCGAAGCTCA',
                   'CTCCTGGCCACAGCTTGAGCTGGGAGGAGGGTGGAGGCTGGGCCGCCTCCTGGACCCCTGCCCTCCCTGCCCGGCCTTCCAAGGCCCGGCAGCCTCAGTCCACTGCTGGGCCTGGAACACGGAGCAGTGGCTGCCCTGCGAGGAGGTGGGTGTCCGGAGTGCTAGCCAGGGTGGGGCTGGGCTAGGGGGAGCCTGATGTCACCCCCATTGTAGGAGGGAGAAGACCAAGGATGAGAAGGGCTTTGGCTTCCCCAAGGTGACCCCCTCTTTGAGCCTAGGCATAGT',
                   'CAGCCTCAGTCCACTGCTGGGCCTGGAACACGGAGCAGTGGCTGCCCTGCGAGGAGGTGGGTGTCCGGAGTGCTAGCCAGGGTGGGGCTGGGCTAGGGGGAGCCTGATGTCACCCCCATTGTAGGAGGGAGAAGACCAAGGATGAGAAGGGCTTTGGCTTCCCCAAGGTGACCCCCTCTTTGAGCCTAGGCATAGT',
                   'AGTCCACTGCTGGGCCTGGAACACGGAGCAGTGGCTGCCCTGCGAGGAGGTGGGTGTCCGGAGTGCTAGCCAGGGTGGGGCTGGGCTAGGGGGAGCCTGATGTCACCCCCATTGTAGGAGGGAGAAGACCAAGGATGAGAAGGGCTTTGGCTTCCCCAAGGTGACCCCCTCTTTGAGCCTAGGCATAGT',
                   'GCTCCCACTGTCTCTCTCCGTCCCTCTGTGTCTCTACCTGCCCACACGCCCCGGTCCTGATGGCTCCAGTCTCCCCTGCAGGTCCTAGAGCAGCTCCAGCAGGATGGCGGCTCCAGCGTCTCTAAGGCCTGCAGGGGGTCCAGCCCCATGGGGGGCGCCCTAGGCCTCCGACAGCTCCCCATCTGTGCTCCTGCCTGCCGGCCATCCTCAGGCCACTCGCC']
